# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q33anHm2YarnYCDlKXnFLqKa8bYCwIlR
"""

a=int(input("enter a number"))
for i in range(2,a):
  if a%i==0:
   print(" not prime")
   break
  else:
    print("prime number")
    break

t=int(input("enter temperature in celcius"))
faren=t*9/5+32
print(t ,faren)

a=input("enter a string")
if a.startswith("p"):
  print("welcome")
else:
  print("no entry")

n=input("enter a paragraph:")
v=("a","e","i","o","u","A","E","I","O","U")
count=0
for i in n:
  if i in v:
    count=count+1
    print("vowels",count)
    break

  else:
    print("no vowels")
    break

n=input("enter a paragraph:")
count=0
for i in n:
  if (i=='a'or i=='e'or i=='i'or i=='o'or i=='u'):

   count+=1
print(count)

n=input("enter a paragraph:")
v=("a","e","i","o","u","A","E","I","O","U")
count=0
for i in n:
  if i in v:
    count=count+1
print("vowels",count)